[project]
name = "tankgame"
version = "0.1.0"
description = "Offline clone of the Roblox Tank Game (Diep.io style)"
readme = "README.md"
authors = [
    { name = "Willem Meints", email = "1550763+wmeints@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pygame-ce>=2.5.8",
]

[project.scripts]
tankgame = "tankgame:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
